#! /bin/bash 
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -q core-24.q
#$ -pe smp 24
#$ -N r4A6_pcm
#$ -l h_rt=960:00:00

#echo $HOSTr4A6_pcm > test-file 
source /home/matma/.bashrc
export PGI_FASTMATH_CPU=sandybridge

g16 input.com &> input.log


